# The `FROM` instruction specifies the base image. You are
# extending the `microsoft/aspnet` image.

FROM microsoft/dotnet:nanoserver

# Next, this Dockerfile creates a directory for your application
RUN mkdir C:\myaspnet462dockerapp

# configure the new site in IIS.
RUN powershell -NoProfile -Command \
    Install-PackageProvider NanoServerPackage; \
	Import-PackageProvider NanoServerPackage; \
	Install-NanoServerPackage -Name Microsoft-NanoServer-Storage-Package; \
	Install-NanoServerPackage -Name Microsoft-NanoServer-IIS-Package; \
#    New-IISSite -Name "ASPNET" -PhysicalPath C:\myaspnet462dockerapp -BindingInformation "*:8000:"

# This instruction tells the container to listen on port 8000. 
# EXPOSE 8000

# The final instruction copies the site you published earlier into the container.
ADD /dotnet462/bin/PublishOutput/ /myaspnet462dockerapp
